// Code generated by counterfeiter. DO NOT EDIT.
//
//lint:file-ignore ST1008 Generated mocks reflect original interface signatures
package mocks

import (
	"sync"
	"time"

	"github.com/grafana/nanogit/metrics"
)

type FakeRecorder struct {
	CacheAccessStub        func(bool)
	cacheAccessMutex       sync.RWMutex
	cacheAccessArgsForCall []struct {
		arg1 bool
	}
	HTTPRequestStub        func(string, int, time.Duration, int)
	hTTPRequestMutex       sync.RWMutex
	hTTPRequestArgsForCall []struct {
		arg1 string
		arg2 int
		arg3 time.Duration
		arg4 int
	}
	ObjectsFetchedStub        func(int, int64)
	objectsFetchedMutex       sync.RWMutex
	objectsFetchedArgsForCall []struct {
		arg1 int
		arg2 int64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRecorder) CacheAccess(arg1 bool) {
	fake.cacheAccessMutex.Lock()
	fake.cacheAccessArgsForCall = append(fake.cacheAccessArgsForCall, struct {
		arg1 bool
	}{arg1})
	stub := fake.CacheAccessStub
	fake.recordInvocation("CacheAccess", []interface{}{arg1})
	fake.cacheAccessMutex.Unlock()
	if stub != nil {
		fake.CacheAccessStub(arg1)
	}
}

func (fake *FakeRecorder) CacheAccessCallCount() int {
	fake.cacheAccessMutex.RLock()
	defer fake.cacheAccessMutex.RUnlock()
	return len(fake.cacheAccessArgsForCall)
}

func (fake *FakeRecorder) CacheAccessCalls(stub func(bool)) {
	fake.cacheAccessMutex.Lock()
	defer fake.cacheAccessMutex.Unlock()
	fake.CacheAccessStub = stub
}

func (fake *FakeRecorder) CacheAccessArgsForCall(i int) bool {
	fake.cacheAccessMutex.RLock()
	defer fake.cacheAccessMutex.RUnlock()
	argsForCall := fake.cacheAccessArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRecorder) HTTPRequest(arg1 string, arg2 int, arg3 time.Duration, arg4 int) {
	fake.hTTPRequestMutex.Lock()
	fake.hTTPRequestArgsForCall = append(fake.hTTPRequestArgsForCall, struct {
		arg1 string
		arg2 int
		arg3 time.Duration
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.HTTPRequestStub
	fake.recordInvocation("HTTPRequest", []interface{}{arg1, arg2, arg3, arg4})
	fake.hTTPRequestMutex.Unlock()
	if stub != nil {
		fake.HTTPRequestStub(arg1, arg2, arg3, arg4)
	}
}

func (fake *FakeRecorder) HTTPRequestCallCount() int {
	fake.hTTPRequestMutex.RLock()
	defer fake.hTTPRequestMutex.RUnlock()
	return len(fake.hTTPRequestArgsForCall)
}

func (fake *FakeRecorder) HTTPRequestCalls(stub func(string, int, time.Duration, int)) {
	fake.hTTPRequestMutex.Lock()
	defer fake.hTTPRequestMutex.Unlock()
	fake.HTTPRequestStub = stub
}

func (fake *FakeRecorder) HTTPRequestArgsForCall(i int) (string, int, time.Duration, int) {
	fake.hTTPRequestMutex.RLock()
	defer fake.hTTPRequestMutex.RUnlock()
	argsForCall := fake.hTTPRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRecorder) ObjectsFetched(arg1 int, arg2 int64) {
	fake.objectsFetchedMutex.Lock()
	fake.objectsFetchedArgsForCall = append(fake.objectsFetchedArgsForCall, struct {
		arg1 int
		arg2 int64
	}{arg1, arg2})
	stub := fake.ObjectsFetchedStub
	fake.recordInvocation("ObjectsFetched", []interface{}{arg1, arg2})
	fake.objectsFetchedMutex.Unlock()
	if stub != nil {
		fake.ObjectsFetchedStub(arg1, arg2)
	}
}

func (fake *FakeRecorder) ObjectsFetchedCallCount() int {
	fake.objectsFetchedMutex.RLock()
	defer fake.objectsFetchedMutex.RUnlock()
	return len(fake.objectsFetchedArgsForCall)
}

func (fake *FakeRecorder) ObjectsFetchedCalls(stub func(int, int64)) {
	fake.objectsFetchedMutex.Lock()
	defer fake.objectsFetchedMutex.Unlock()
	fake.ObjectsFetchedStub = stub
}

func (fake *FakeRecorder) ObjectsFetchedArgsForCall(i int) (int, int64) {
	fake.objectsFetchedMutex.RLock()
	defer fake.objectsFetchedMutex.RUnlock()
	argsForCall := fake.objectsFetchedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRecorder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRecorder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Recorder = new(FakeRecorder)
