// Code generated by counterfeiter. DO NOT EDIT.
//
//lint:file-ignore ST1008 Generated mocks reflect original interface signatures
package mocks

import (
	"context"
	"sync"

	"github.com/grafana/nanogit/metrics"
)

type FakeRecorder struct {
	CacheAccessStub        func(context.Context, metrics.CacheAccessEvent)
	cacheAccessMutex       sync.RWMutex
	cacheAccessArgsForCall []struct {
		arg1 context.Context
		arg2 metrics.CacheAccessEvent
	}
	HTTPRequestStub        func(context.Context, metrics.HTTPRequestEvent)
	hTTPRequestMutex       sync.RWMutex
	hTTPRequestArgsForCall []struct {
		arg1 context.Context
		arg2 metrics.HTTPRequestEvent
	}
	ObjectsFetchedStub        func(context.Context, metrics.ObjectsFetchedEvent)
	objectsFetchedMutex       sync.RWMutex
	objectsFetchedArgsForCall []struct {
		arg1 context.Context
		arg2 metrics.ObjectsFetchedEvent
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRecorder) CacheAccess(arg1 context.Context, arg2 metrics.CacheAccessEvent) {
	fake.cacheAccessMutex.Lock()
	fake.cacheAccessArgsForCall = append(fake.cacheAccessArgsForCall, struct {
		arg1 context.Context
		arg2 metrics.CacheAccessEvent
	}{arg1, arg2})
	stub := fake.CacheAccessStub
	fake.recordInvocation("CacheAccess", []interface{}{arg1, arg2})
	fake.cacheAccessMutex.Unlock()
	if stub != nil {
		fake.CacheAccessStub(arg1, arg2)
	}
}

func (fake *FakeRecorder) CacheAccessCallCount() int {
	fake.cacheAccessMutex.RLock()
	defer fake.cacheAccessMutex.RUnlock()
	return len(fake.cacheAccessArgsForCall)
}

func (fake *FakeRecorder) CacheAccessCalls(stub func(context.Context, metrics.CacheAccessEvent)) {
	fake.cacheAccessMutex.Lock()
	defer fake.cacheAccessMutex.Unlock()
	fake.CacheAccessStub = stub
}

func (fake *FakeRecorder) CacheAccessArgsForCall(i int) (context.Context, metrics.CacheAccessEvent) {
	fake.cacheAccessMutex.RLock()
	defer fake.cacheAccessMutex.RUnlock()
	argsForCall := fake.cacheAccessArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRecorder) HTTPRequest(arg1 context.Context, arg2 metrics.HTTPRequestEvent) {
	fake.hTTPRequestMutex.Lock()
	fake.hTTPRequestArgsForCall = append(fake.hTTPRequestArgsForCall, struct {
		arg1 context.Context
		arg2 metrics.HTTPRequestEvent
	}{arg1, arg2})
	stub := fake.HTTPRequestStub
	fake.recordInvocation("HTTPRequest", []interface{}{arg1, arg2})
	fake.hTTPRequestMutex.Unlock()
	if stub != nil {
		fake.HTTPRequestStub(arg1, arg2)
	}
}

func (fake *FakeRecorder) HTTPRequestCallCount() int {
	fake.hTTPRequestMutex.RLock()
	defer fake.hTTPRequestMutex.RUnlock()
	return len(fake.hTTPRequestArgsForCall)
}

func (fake *FakeRecorder) HTTPRequestCalls(stub func(context.Context, metrics.HTTPRequestEvent)) {
	fake.hTTPRequestMutex.Lock()
	defer fake.hTTPRequestMutex.Unlock()
	fake.HTTPRequestStub = stub
}

func (fake *FakeRecorder) HTTPRequestArgsForCall(i int) (context.Context, metrics.HTTPRequestEvent) {
	fake.hTTPRequestMutex.RLock()
	defer fake.hTTPRequestMutex.RUnlock()
	argsForCall := fake.hTTPRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRecorder) ObjectsFetched(arg1 context.Context, arg2 metrics.ObjectsFetchedEvent) {
	fake.objectsFetchedMutex.Lock()
	fake.objectsFetchedArgsForCall = append(fake.objectsFetchedArgsForCall, struct {
		arg1 context.Context
		arg2 metrics.ObjectsFetchedEvent
	}{arg1, arg2})
	stub := fake.ObjectsFetchedStub
	fake.recordInvocation("ObjectsFetched", []interface{}{arg1, arg2})
	fake.objectsFetchedMutex.Unlock()
	if stub != nil {
		fake.ObjectsFetchedStub(arg1, arg2)
	}
}

func (fake *FakeRecorder) ObjectsFetchedCallCount() int {
	fake.objectsFetchedMutex.RLock()
	defer fake.objectsFetchedMutex.RUnlock()
	return len(fake.objectsFetchedArgsForCall)
}

func (fake *FakeRecorder) ObjectsFetchedCalls(stub func(context.Context, metrics.ObjectsFetchedEvent)) {
	fake.objectsFetchedMutex.Lock()
	defer fake.objectsFetchedMutex.Unlock()
	fake.ObjectsFetchedStub = stub
}

func (fake *FakeRecorder) ObjectsFetchedArgsForCall(i int) (context.Context, metrics.ObjectsFetchedEvent) {
	fake.objectsFetchedMutex.RLock()
	defer fake.objectsFetchedMutex.RUnlock()
	argsForCall := fake.objectsFetchedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRecorder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRecorder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ metrics.Recorder = new(FakeRecorder)
